-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.departments
(
    dept_no character varying(4) NOT NULL,
    dept_name character varying(20) NOT NULL,
    PRIMARY KEY (dept_no, dept_name)
);

COMMENT ON TABLE public.departments
    IS 'Table that includes dept number (CK) and Dept name (CK)';

CREATE TABLE IF NOT EXISTS public.dept_emp
(
    emp_no character varying(6) NOT NULL,
    dept_no character varying(4) NOT NULL,
    PRIMARY KEY (emp_no)
);

COMMENT ON TABLE public.dept_emp
    IS 'dept emp table that contains emp_no and dept_no';

CREATE TABLE IF NOT EXISTS public.dept_manager
(
    dept_no character varying(4) NOT NULL,
    emp_no character varying(6)[] NOT NULL,
    PRIMARY KEY (emp_no)
);

COMMENT ON TABLE public.dept_manager
    IS 'dept manager table that contains dept no and emp no';

CREATE TABLE IF NOT EXISTS public.employees
(
    emp_no character varying(6) NOT NULL,
    emp_title_id character varying(5) NOT NULL,
    birth_date date NOT NULL,
    first_name character varying NOT NULL,
    last_name character varying NOT NULL,
    sex character varying(1) NOT NULL,
    hire_date date NOT NULL
);

COMMENT ON TABLE public.employees
    IS 'employees table that contains emp no, emp title id, birth date, first name, last name, sex and hire date';

CREATE TABLE IF NOT EXISTS public.salaries
(
    emp_no character varying(6) NOT NULL,
    salary integer NOT NULL
);

COMMENT ON TABLE public.salaries
    IS 'table that contains emp no and salary';

CREATE TABLE IF NOT EXISTS public.titles
(
    title_id character varying(5) NOT NULL,
    title character varying NOT NULL,
    PRIMARY KEY (title)
);

COMMENT ON TABLE public.titles
    IS 'table to hold title id and title name';

ALTER TABLE IF EXISTS public.departments
    ADD FOREIGN KEY (dept_no)
    REFERENCES public.dept_emp (dept_no) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.dept_emp
    ADD FOREIGN KEY (emp_no)
    REFERENCES public.dept_manager (emp_no) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.dept_manager
    ADD FOREIGN KEY (dept_no)
    REFERENCES public.employees (emp_no) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.salaries
    ADD FOREIGN KEY (emp_no)
    REFERENCES public.employees (emp_no) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.titles
    ADD FOREIGN KEY (title_id)
    REFERENCES public.employees (emp_title_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;